import { Item, User, } from '@/types/auction';

export const PORT = 5000
export const SERVER = `192.168.130.199`
export const URL = `http://${SERVER}:${PORT}/api`
export const BASE_URL = `http://${SERVER}:${PORT}`
export const URL_AUTH = `http://${SERVER}:${PORT}/api/auth`
export const PAYMENT_API_KEY = 'pk_test_340ca76dd262b6d620fac1f8c494a59212093fb1'


// Mock data for development
export const MOCK_ITEMS: Item[] = [
    {
        _id: '1',
        id: '1',
        title: 'MacBook Pro 2021',
        description: 'M1 Pro, 16GB RAM, 512GB SSD, Space Gray, excellent condition',
        images: ['https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
        category: 'Electronics',
        condition: 'Like New',
        startingprice: 899.99,
        currentprice: 950.00,
        seller: {
            _id: 'user1',
            id: 'user1',
            email: 'john@college.edu',
            name: 'John Smith',
            campus: 'State University',
            createdAt: '2023-01-15T12:00:00Z',
            roles: ['Student'],
            phone: '123-456-7890',
        },
        startdate: new Date('2025-05-01T12:00:00Z'),
        enddate: new Date('2025-05-08T12:00:00Z'),
        status: 'Active',
        bids: [
            {
                id: 'bid1',
                item: '1',
                bidder: {
                    _id: 'user2',
                    id: 'user2',
                    email: 'alicejohnson@college.edu',
                    name: 'Alice Johnson',
                    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                    campus: 'State University',
                    createdAt: '2023-02-20T14:30:00Z',
                    roles: ['Student'],
                    phone: '123-456-7890',
                },
                amount: 920.00,
                createdAt: '2025-05-02T14:30:00Z'
            },
            {
                id: 'bid2',
                item: '1',
                bidder: {
                    _id: 'user3',
                    id: 'user3',
                    email: 'you@college.edu',
                    name: 'John Doe',
                    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                    campus: 'State University',
                    createdAt: '2023-01-15T12:00:00Z',
                    roles: ['Student'],
                    phone: '123-456-7890',
                },
                amount: 950.00,
                createdAt: '2025-05-03T16:45:00Z'
            },
        ],
        campus: 'State University',
        createdAt: new Date('2025-05-01T12:00:00Z'),
    },
    {
        _id: '2',
        id: '2',
        title: 'Physics Textbook',
        description: 'University Physics with Modern Physics, 14th Edition',
        images: ['https://images.pexels.com/photos/159497/school-notebook-binders-notepad-159497.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
        category: 'Books',
        condition: 'Good',
        startingprice: 45.00,
        currentprice: 50.00,
        seller: {
            id: 'user2',
            _id: 'user2',
            email: 'alice@college.edu',
            name: 'Alice Johnson',
            campus: 'State University',
            createdAt: '2023-02-20T14:30:00Z',
            roles: ['Student'],
            phone: '123-456-7890',
        },
        startdate: new Date('2025-05-02T09:00:00Z'),
        enddate: new Date('2025-05-09T09:00:00Z'),
        status: 'Active',
        bids: [
            {
                id: 'bid3',
                item: '2',
                bidder: {
                    id: 'user1',
                    _id: 'user1',
                    email: 'alexmorgan@gmail.edu',
                    name: 'Alex Morgan',
                    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                    campus: 'State University',
                    createdAt: '2023-01-01T12:00:00Z',
                    roles: ['Student'],
                    phone: '123-456-7890',
                },
                amount: 50.00,
                createdAt: '2025-05-03T10:15:00Z'
            },
        ],
        campus: 'State University',
        createdAt: new Date('2025-05-02T09:00:00Z'),
    },
    {
        _id: '3',
        id: '3',
        title: 'Desk Lamp',
        description: 'LED desk lamp with wireless charging pad',
        images: ['https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
        category: 'Furniture',
        condition: 'New',
        startingprice: 35.00,
        currentprice: 35.00,
        seller: {
            id: 'user3',
            _id: 'user3',
            email: 'mike@college.edu',
            name: 'Mike Brown',
            campus: 'State University',
            createdAt: '2023-03-10T10:15:00Z',
            roles: ['Student'],
            phone: '123-456-7890',
        },
        startdate: new Date('2025-05-02T09:00:00Z'),
        enddate: new Date('2025-05-09T09:00:00Z'),
        status: 'Active',
        bids: [],
        campus: 'State University',
        createdAt: new Date('2025-05-03T15:00:00Z'),
    },
    {
        _id: '4',
        id: '4',
        title: 'Canon EOS R Camera',
        description: 'Mirrorless digital camera with 24-105mm lens, includes case and SD card',
        images: ['https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
        category: 'Photography',
        condition: 'Like New',
        startingprice: 1200.00,
        currentprice: 1300.00,
        seller: {
            id: 'user1',
            _id: 'user1',
            email: 'john@college.edu',
            name: 'John Smith',
            campus: 'State University',
            createdAt: '2023-01-15T12:00:00Z',
            roles: ['Student'],
            phone: '123-456-7890',
        },
        startdate: new Date('2025-05-02T09:00:00Z'),
        enddate: new Date('2025-05-09T09:00:00Z'),
        status: 'Active',
        bids: [
            {
                id: 'bid4',
                item: '4',
                bidder: {
                    id: 'user2',
                    _id: 'user2',
                    email: 'alicejohnson@college.edu',
                    name: 'Alice Johnson',
                    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                    campus: 'State University',
                    createdAt: '2023-02-20T14:30:00Z',
                    roles: ['Student'],
                    phone: '123-456-7890',
                },
                amount: 1250.00,
                createdAt: '2025-05-03T13:20:00Z'
            },
            {
                id: 'bid5',
                item: '4',
                bidder: {
                    id: 'user3',
                    _id: 'user3',
                    email: 'you@college.edu',
                    name: 'John Doe',
                    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                    campus: 'State University',
                    createdAt: '2023-01-15T12:00:00Z',
                    roles: ['Student'],
                    phone: '123-456-7890',
                },
                amount: 1300.00,
                createdAt: '2025-05-04T09:45:00Z'
            },
        ],
        campus: 'State University',
        createdAt: new Date('2025-05-02T10:00:00Z'),
    },
];

export const MOCK_USERS: User[] = [
    {
        id: 'user1',
        _id: 'user1',
        email: 'alexmorgan@gmail.edu',
        name: 'Alex Morgan',
        avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        campus: 'State University',
        createdAt: '2023-01-01T12:00:00Z',
        roles: ['Student'],
        phone: '123-456-7890',
    },
    {
        id: 'user2',
        _id: 'user2',
        email: 'alicejohnson@college.edu',
        name: 'Alice Johnson',
        avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        campus: 'State University',
        createdAt: '2023-02-20T14:30:00Z',
        roles: ['Student'],
        phone: '123-456-7890',
    },
    {
        id: 'user3',
        _id: 'user3',
        email: 'you@college.edu',
        name: 'John Doe',
        avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        campus: 'State University',
        createdAt: '2023-01-15T12:00:00Z',
        roles: ['Student'],
        phone: '123-456-7890',
    },
];

// Mock data for the conversation
export const MOCK_CONVERSATION = {
    id: 'conv1',
    otherUser: {
        _id: 'user2',
        id: 'user2',
        email: 'alice@college.edu',
        name: 'Alice Johnson',
        avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        campus: 'State University',
        createdAt: '2023-02-20T14:30:00Z',
        roles: ['User'],
    },
    currentUser: {
        id: 'user1',
        email: 'you@college.edu',
        name: 'You',
        avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        campus: 'State University',
        createdAt: '2023-01-15T12:00:00Z',
    },
    messages: [
        {
            id: 'msg1',
            senderId: 'user2',
            receiverId: 'user1',
            content: 'Hi there! Is the MacBook still available?',
            read: true,
            createdAt: '2025-05-04T14:30:00Z',
        },
        {
            id: 'msg2',
            senderId: 'user1',
            receiverId: 'user2',
            content: 'Yes it is! Are you interested?',
            read: true,
            createdAt: '2025-05-04T14:35:00Z',
        },
        {
            id: 'msg3',
            senderId: 'user2',
            receiverId: 'user1',
            content: 'Definitely! Would you accept $900 for it?',
            read: true,
            createdAt: '2025-05-04T14:40:00Z',
        },
        {
            id: 'msg4',
            senderId: 'user1',
            receiverId: 'user2',
            content: "I'd prefer to stick with the auction, but you can place a bid right now if you'd like to secure it.",
            read: true,
            createdAt: '2025-05-04T14:45:00Z',
        },
        {
            id: 'msg5',
            senderId: 'user2',
            receiverId: 'user1',
            content: 'Okay, I understand. Can I see it in person before I bid?',
            read: true,
            createdAt: '2025-05-04T15:00:00Z',
        },
    ],
};

// Mock user's saved/favorited items
export const MOCK_FAVORITES: Item[] = [
    {
        _id: '2',
        id: '2',
        title: 'Physics Textbook',
        description: 'University Physics with Modern Physics, 14th Edition',
        images: ['https://images.pexels.com/photos/159497/school-notebook-binders-notepad-159497.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
        category: 'Books',
        condition: 'Good',
        startingprice: 45.00,
        currentprice: 50.00,
        seller: {
            id: 'user2',
            _id: 'user2',
            email: 'alice@college.edu',
            name: 'Alice Johnson',
            campus: 'State University',
            createdAt: '2023-02-20T14:30:00Z',
            roles: ['Student'],
            phone: '123-456-7890',
        },
        startdate: new Date('2025-05-02T09:00:00Z'),
        enddate: new Date('2025-05-09T09:00:00Z'),
        status: 'Active',
        bids: [
            {
                id: 'bid3',
                item: '2',
                bidder: {
                    id: 'user1',
                    _id: 'user1',
                    email: 'alexmorgan@gmail.edu',
                    name: 'Alex Morgan',
                    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                    campus: 'State University',
                    createdAt: '2023-01-01T12:00:00Z',
                    roles: ['Student'],
                    phone: '123-456-7890',
                },
                amount: 50.00,
                createdAt: '2025-05-03T10:15:00Z'
            },
        ],
        campus: 'State University',
        createdAt: new Date('2025-05-02T09:00:00Z'),
    },
];

// Mock user's items data
export const MOCK_USER_ITEMS: Item[] = [
    {
        _id: '1',
        id: '1',
        title: 'MacBook Pro 2021',
        description: 'M1 Pro, 16GB RAM, 512GB SSD, Space Gray, excellent condition',
        images: ['https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
        category: 'Electronics',
        condition: 'Like New',
        startingprice: 899.99,
        currentprice: 950.00,
        seller: MOCK_USERS[0],
        startdate: new Date('2025-05-01T12:00:00Z'),
        enddate: new Date('2025-05-08T12:00:00Z'),
        status: 'Active',
        bids: [
            {
                id: 'bid1',
                item: '1',
                bidder: {
                    id: 'user2',
                    _id: 'user2',
                    email: 'alicejohnson@college.edu',
                    name: 'Alice Johnson',
                    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                    campus: 'State University',
                    createdAt: '2023-02-20T14:30:00Z',
                    roles: ['Student'],
                    phone: '123-456-7890',
                },
                amount: 920.00,
                createdAt: '2025-05-02T14:30:00Z'
            },
            {
                id: 'bid2',
                item: '1',
                bidder: {
                    id: 'user3',
                    _id: 'user3',
                    email: 'you@college.edu',
                    name: 'John Doe',
                    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                    campus: 'State University',
                    createdAt: '2023-01-15T12:00:00Z',
                    roles: ['Student'],
                    phone: '123-456-7890',
                },
                amount: 950.00,
                createdAt: '2025-05-03T16:45:00Z'
            },
        ],
        campus: 'State University',
        createdAt: new Date('2025-05-01T12:00:00Z'),
    },
    {
        _id: '2',
        id: '4',
        title: 'Canon EOS R Camera',
        description: 'Mirrorless digital camera with 24-105mm lens, includes case and SD card',
        images: ['https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
        category: 'Photography',
        condition: 'Like New',
        startingprice: 1200.00,
        currentprice: 1300.00,
        seller: MOCK_USERS[0],
        startdate: new Date('2025-05-02T09:00:00Z'),
        enddate: new Date('2025-05-09T09:00:00Z'),
        status: 'Active',
        bids: [
            {
                id: 'bid4',
                item: '4',
                bidder: {
                    id: 'user2',
                    _id: 'user2',
                    email: 'alicejohnson@college.edu',
                    name: 'Alice Johnson',
                    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                    campus: 'State University',
                    createdAt: '2023-02-20T14:30:00Z',
                    roles: ['Student'],
                    phone: '123-456-7890',
                },
                amount: 1250.00,
                createdAt: '2025-05-03T13:20:00Z'
            },
            {
                id: 'bid5',
                item: '4',
                bidder: {
                    id: 'user3',
                    _id: 'user3',
                    email: 'you@college.edu',
                    name: 'John Doe',
                    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                    campus: 'State University',
                    createdAt: '2023-01-15T12:00:00Z',
                    roles: ['Student'],
                    phone: '123-456-7890',
                },
                amount: 1300.00,
                createdAt: '2025-05-04T09:45:00Z'
            },
        ],
        campus: 'State University',
        createdAt: new Date('2025-05-02T10:00:00Z'),
    },
];

export const images = {
    logo: require('../assets/images/logo.jpg'),
    screen: require('../assets/images/splash1.jpg'),
    splash1: require('../assets/images/splash1.jpg'),
    spalsh2: require('../assets/images/splash2.jpg'),
    splash3: require('../assets/images/splash3.jpg'),
    splash4: require('../assets/images/splash4.jpg'),
    splash5: require('../assets/images/splash5.jpg'),
    profile: require('../assets/images/profile.png'),
}